-- Original table schema
CREATE TABLE [TB_REAL_PRICE] (
    [code] varchar(50) NOT NULL,
	[股票名] varchar(50) NOT NULL,
	[开盘价]   float,
	[昨收盘价] float,
	[当前价]	float,
	[最高价]	float,
	[最低价]	float,
	[买入价]	float,
	[卖出价]	float,
	[成交量]	float,
	[成交额]	float,
	[买一量]	float,
	[买一价]	float,
	[买二量]	float,
	[买二价]	float,
	[买三量]	float,
	[买三价]	float,
	[买四量]	float,
	[买四价]	float,
	[买五量]	float,
	[买五价]	float,
	[卖一量]	float,
	[卖一价]	float,
	[卖二量]	float,
	[卖二价]	float,
	[卖三量]	float,
	[卖三价]	float,
	[卖四量]	float,
	[卖四价]	float,
	[卖五量]	float,
	[卖五价]	float,
	[时间] datetime
);
